# Docker Compose (v2)

version: '2'

services:

  cli_scripts:
    build:
      context: images/ci
      args:
        - BASE_IMAGE=${BASE_IMAGE}
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTP_PROXY}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTP_PROXY}
        - NO_PROXY=${NO_PROXY}
        - no_proxy=${NO_PROXY}
    environment:
      - DRUPAL_SETTINGS=production
      - http_proxy=${HTTP_PROXY}
      - https_proxy=${HTTP_PROXY}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTP_PROXY}
      - NO_PROXY=${NO_PROXY}
      - no_proxy=${NO_PROXY}
    volumes:
      - ./conf/drupal/settings.php:/var/www/html/sites/default/settings.php:ro
      - files_data:/var/www/html/sites/default/files
      - files_private_data:/var/www/files_private
    container_name: ${DOCKER_NAME}_web_scripts

  web_ci:
    build:
      context: images/ci
      args:
        - BASE_IMAGE=${BASE_IMAGE}
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTP_PROXY}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTP_PROXY}
        - NO_PROXY=${NO_PROXY}
        - no_proxy=${NO_PROXY}
    environment:
      - DRUPAL_SETTINGS=production
      - http_proxy=${HTTP_PROXY}
      - https_proxy=${HTTP_PROXY}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTP_PROXY}
      - NO_PROXY=${NO_PROXY}
      - no_proxy=${NO_PROXY}
    ports:
      - "9000"
    container_name: ${DOCKER_NAME}_web

  web_dev:
    build:
      context: images/dev
      args:
        - BASE_IMAGE=${BASE_IMAGE}
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTP_PROXY}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTP_PROXY}
        - NO_PROXY=${NO_PROXY}
        - no_proxy=${NO_PROXY}
    environment:
      - DRUPAL_SETTINGS=development
      - http_proxy=${HTTP_PROXY}
      - https_proxy=${HTTP_PROXY}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTP_PROXY}
      - NO_PROXY=solr,${NO_PROXY}
      - no_proxy=solr,${NO_PROXY}
    volumes:
      - ..:/var/www
    ports:
      - "9000"
    container_name: ${DOCKER_NAME}_web

  cli:
    build:
      context: images/cli
      args:
        - BASE_IMAGE=${BASE_IMAGE}
    environment:
      - http_proxy=${HTTP_PROXY}
      - https_proxy=${HTTP_PROXY}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_proxy=${HTTP_PROXY}
      - NO_PROXY=hub,solr,${NO_PROXY}
      - no_proxy=hub,solr,${NO_PROXY}
    container_name: ${DOCKER_NAME}_cli

  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"
    container_name: ${DOCKER_NAME}_db
    command: mysqld --max_allowed_packet=256M --innodb_buffer_pool_size=4096M --innodb_buffer_pool_instances=4 --table_definition_cache=4096 --table_open_cache=8192 --innodb_flush_log_at_trx_commit=2

  nginx_dev:
    image: nginx:alpine
    volumes:
     - ../html:/var/www/html
     - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '8080:80'
    restart: always
    container_name: ${DOCKER_NAME}_nginx

  nginx_ci:
    build:
      context: images/nginx
      args:
        - BASE_IMAGE=${BASE_IMAGE}
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTP_PROXY}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTP_PROXY}
        - NO_PROXY=${NO_PROXY}
        - no_proxy=${NO_PROXY}
    volumes:
      - files_data:/var/www/html/sites/default/files
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'
    restart: always
    container_name: ${DOCKER_NAME}_nginx

  cron:
    build:
      context: images/cron
      args:
        - BASE_IMAGE=${BASE_IMAGE}
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTP_PROXY}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTP_PROXY}
        - NO_PROXY=${NO_PROXY}
        - no_proxy=${NO_PROXY}
    environment:
      - DRUPAL_SETTINGS=development
      - http_proxy=${HTTP_PROXY}
      - https_proxy=${HTTP_PROXY}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTP_PROXY}
      - NO_PROXY=${NO_PROXY}
      - no_proxy=${NO_PROXY}
    volumes:
      - ..:/var/www
    container_name: ${DOCKER_NAME}_cron

  hub:
    image: drupalcomposer/selenium:hub
    ports:
      - "4444:4444"
    container_name: ${DOCKER_NAME}_hub

  firefox:
    image: drupalcomposer/selenium:node-firefox
    environment:
     - http_proxy=http://proxy:80/
     - https_proxy=http://proxy:80/
     - HTTP_PROXY=http://proxy:80/
     - HTTPS_PROXY=http://proxy:80/
     - NO_PROXY=nginx,${NO_PROXY}
     - no_proxy=nginx,${NO_PROXY}
    container_name: ${DOCKER_NAME}_firefox

  proxy:
    build:
      context: images/proxy
      args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTP_PROXY}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTP_PROXY}
        - NO_PROXY=${NO_PROXY}
        - no_proxy=${NO_PROXY}
    environment:
      - http_proxy=${HTTP_PROXY}
      - https_proxy=${HTTP_PROXY}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTP_PROXY}
      - NO_PROXY=${NO_PROXY}
      - no_proxy=${no_proxy}
    container_name: ${DOCKER_NAME}_proxy

  mailhog:
    image: mailhog/mailhog
    hostname: mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
    container_name: ${DOCKER_NAME}_mailhog

  solr:
    image: solr:8
    hostname: solr
    ports:
      - "8983:8983"
    command: ""
    volumes:
      - ../solr/solr_core:/var/solr/data/solr_core
    container_name: ${DOCKER_NAME}_solr
